### ISSUE TITLE
How to get gradle other versions?

### ISSUE THREAD

**Issue by Pinned** [xiaoyur347/gradlew#1]

**Comment by xiaoyur347** [comment]
Hello, you can download the lastest gradle all zip, 
src/cli/org/gradle/cli is my src/main/java/org/gradle/cli
src/wrapper/org/gradle/wrapper is my src/main/java/org/gradle/wrapper

And I compare the gradle 4.2.1 and gradle 2.14.1.
There is no difference for cli and some difference for wrapper.

**Comment by Pinned** [comment]
Thank you.
